# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
User.create(name: "Cho", username: "Cho", password: "Cho")
User.create(name: "Rafia", username: "Rafia", password: "Rafia")
Product.create(name: "Calm + Restore Triple Oat Hydrating Face Serum for Sensitive Skin", category: "Serum", brand: "Aveeno", image: "https://m.media-amazon.com/images/I/71uEPq-7ivL._SL1500_.jpg", price_size: "$19.67/1 fl. oz")
Product.create(name: "Snail Mucin 92% Repair Cream", category: "Moisturizer", brand: "COSRX", image: "https://m.media-amazon.com/images/I/7135DSnMj+L._SL1500_.jpg", price_size: "$22.73/3.52 oz, 100g")
Review.create(score: 4, comments: "I have very sensitive dry skin and i absolutely love this there’s really isn’t a sent to it just smells like oats which i like.", tips: "The product is very suitable for sensitive skin", picture: "https://myskincareregimehome.files.wordpress.com/2022/06/wp-1656361796370.jpg", product_id: 1, user_id: 1)
Review.create(score: 5, comments: "After using it near daily for about a week, I love this stuff.", tips: "This should probably be used as a supplement to your normal moisturizer, not a replacement.", picture: "https://i0.wp.com/blog.ebunoluwole.com/wp-content/uploads/2021/01/IMG_1944.jpg?resize=1024%2C683&ssl=1", product_id: 2, user_id: 2)

Ingredient.create(name: "Water", ewg_rating: 1, toxic: false, irritant: false, skin_type: "", functional: "")
Ingredient.create(name: "Glycerin",ewg_rating: 1, toxic: false, irritant: false, skin_type: "", functional: "")
Ingredient.create(name: "Butylene Glycol",ewg_rating: 1, toxic: false, irritant: false, skin_type: "Good for Dry Skin", functional: "")
Ingredient.create(name: "Bis-PEG-18 Methyl Ether Dimethyl Silane",ewg_rating: 3, toxic: false, irritant: false, skin_type: "", functional: "")
Ingredient.create(name: "Isodecyl Neopentanoate",ewg_rating: 1, toxic: false, irritant: false, skin_type: "", functional: "")
Ingredient.create(name: "Pentaerythrityl Tetraethylhexanoate",ewg_rating: 1, toxic: false, irritant: false, skin_type: "", functional: "")
Ingredient.create(name: "Ethylhexylglycerin",ewg_rating: 2, toxic: false, irritant: false, skin_type: "", functional: "")
Ingredient.create(name: "Phenoxyethanol",ewg_rating: 4, toxic: false, irritant: false, skin_type: "", functional: "")
Ingredient.create(name: "Ammonium Acryloyldimethyltaurate/VP Copolymer",ewg_rating: 4, toxic: false, irritant: false, skin_type: "", functional: "")
Ingredient.create(name: "Chlorphenesin",ewg_rating: 3, toxic: false, irritant: false, skin_type: "", functional: "")
Ingredient.create(name: "Dimethicone",ewg_rating: 3, toxic: false, irritant: false, skin_type: "", functional: "")
Ingredient.create(name: "Succinoglycan",ewg_rating: 1, toxic: false, irritant: false, skin_type: "", functional: "")
Ingredient.create(name: "Chrysanthemum Parthenium (Feverfew) Flower/Leaf/Stem Juice",ewg_rating: 1, toxic: false, irritant: false, skin_type: "", functional: "")
Ingredient.create(name: "Avena Sativa (Oat) Kernel Flour",ewg_rating: 1, toxic: false, irritant: false, skin_type: "", functional: "")
Ingredient.create(name: "Avena Sativa (Oat) Kernel Oil",ewg_rating: 1, toxic: false, irritant: false, skin_type: "", functional: "")
Ingredient.create(name: "Acrylates/C10-30 Alkyl Acrylate Crosspolymer",ewg_rating: 1, toxic: false, irritant: false, skin_type: "", functional: "")
Ingredient.create(name: "Dimethiconol",ewg_rating: 1, toxic: false, irritant: false, skin_type: "", functional: "")
Ingredient.create(name: "Sodium Hydroxide",ewg_rating: 4, toxic: false, irritant: false, skin_type: "", functional: "")
Ingredient.create(name: "Avena Sativa (Oat) Kernel Extract", ewg_rating: 1, toxic: false, irritant: false, skin_type: "", functional: "")

Ingredient.create(name: "Snail Secretion Filtrate", ewg_rating: 1, toxic: false, irritant: false, skin_type: "", functional: "")
Ingredient.create(name: "Betaine", ewg_rating: 1, toxic: false, irritant: false, skin_type: "", functional: "")
Ingredient.create(name: "Caprylic/Capric Triglyceride", ewg_rating: 1, toxic: false, irritant: false, skin_type: "", functional: "")
Ingredient.create(name: "Cetearyl Olivate", ewg_rating: 1, toxic: false, irritant: false, skin_type: "", functional: "")
Ingredient.create(name: "Sorbitan Olivate", ewg_rating: 1, toxic: false, irritant: false, skin_type: "", functional: "")
Ingredient.create(name: "Cetearyl Alcohol", ewg_rating: 1, toxic: false, irritant: false, skin_type: "", functional: "")
Ingredient.create(name: "Carbomer", ewg_rating: 1, toxic: false, irritant: false, skin_type: "", functional: "")
Ingredient.create(name: "Arginine", ewg_rating: 1, toxic: false, irritant: false, skin_type: "", functional: "")
Ingredient.create(name: "Sodium Polyacrylate", ewg_rating: 2, toxic: false, irritant: false, skin_type: "", functional: "")
Ingredient.create(name: "Sodium Hyaluronate", ewg_rating: 1, toxic: false, irritant: false, skin_type: "Good for Dry Skin", functional: "")
Ingredient.create(name: "Stearic Acid", ewg_rating: 1, toxic: false, irritant: false, skin_type: "Not good for oily skin", functional: "")
Ingredient.create(name: "Allantoin", ewg_rating: 1, toxic: false, irritant: false, skin_type: "Good for oily and sensitive skin", functional: "")
Ingredient.create(name: "Panthenol", ewg_rating: 1, toxic: false, irritant: false, skin_type: "Good for Dry Skin", functional: "")
Ingredient.create(name: "Xanthan Gum", ewg_rating: 1, toxic: false, irritant: false, skin_type: "", functional: "")
Ingredient.create(name: "Ethyl Hexanediol", ewg_rating: 3, toxic: false, irritant: true, skin_type: "", functional: "")
Ingredient.create(name: "Adenosine", ewg_rating: 1, toxic: false, irritant: false, skin_type: "", functional: "Anti-wrinkle")
ProIng.create(product_id:1, ingredient_id:1)
ProIng.create(product_id:1, ingredient_id:2)
ProIng.create(product_id:1, ingredient_id:3)
ProIng.create(product_id:1, ingredient_id:4)
ProIng.create(product_id:1, ingredient_id:5)
ProIng.create(product_id:1, ingredient_id:6)
ProIng.create(product_id:1, ingredient_id:7)
ProIng.create(product_id:1, ingredient_id:8)
ProIng.create(product_id:1, ingredient_id:9)
ProIng.create(product_id:1, ingredient_id:10)
ProIng.create(product_id:1, ingredient_id:11)
ProIng.create(product_id:1, ingredient_id:12)
ProIng.create(product_id:1, ingredient_id:13)
ProIng.create(product_id:1, ingredient_id:14)
ProIng.create(product_id:1, ingredient_id:15)
ProIng.create(product_id:1, ingredient_id:16)
ProIng.create(product_id:1, ingredient_id:17)
ProIng.create(product_id:1, ingredient_id:18)
ProIng.create(product_id:1, ingredient_id:19)

ProIng.create(product_id:2, ingredient_id:20)
ProIng.create(product_id:2, ingredient_id:21)
ProIng.create(product_id:2, ingredient_id:22)
ProIng.create(product_id:2, ingredient_id:23)
ProIng.create(product_id:2, ingredient_id:24)
ProIng.create(product_id:2, ingredient_id:25)
ProIng.create(product_id:2, ingredient_id:26)
ProIng.create(product_id:2, ingredient_id:27)
ProIng.create(product_id:2, ingredient_id:11)
ProIng.create(product_id:2, ingredient_id:28)
ProIng.create(product_id:2, ingredient_id:8)
ProIng.create(product_id:2, ingredient_id:29)
ProIng.create(product_id:2, ingredient_id:30)
ProIng.create(product_id:2, ingredient_id:31)
ProIng.create(product_id:2, ingredient_id:32)
ProIng.create(product_id:2, ingredient_id:33)
ProIng.create(product_id:2, ingredient_id:34)
ProIng.create(product_id:2, ingredient_id:35)